require 'insight/instrumentation/instrument'
require 'insight/instrumentation/probe'
require 'insight/instrumentation/client'
require 'insight/instrumentation/setup'
require 'insight/instrumentation/package-definition'
require 'insight/instrumentation/probe-definition'
